import type { ResumeData, SectionConfig } from "../types";

const DEFAULT_SECTION_ORDER: SectionConfig[] = [
    { id: "sec-personal", type: "personal-info", title: "Personal Info", visible: true },
    { id: "sec-skills", type: "skills", title: "Skills", visible: true },
    { id: "sec-experience", type: "experience", title: "Experience", visible: true },
    { id: "sec-education", type: "education", title: "Education", visible: true },
    { id: "sec-projects", type: "projects", title: "Projects", visible: true },
    { id: "sec-additional", type: "additional-experience", title: "Additional Experience", visible: true },
    { id: "sec-certifications", type: "certifications", title: "Certifications", visible: true },
    { id: "sec-languages", type: "languages", title: "Languages", visible: false },
    { id: "sec-findme", type: "find-me-online", title: "Find Me Online", visible: true },
];

export function createDefaultResume(): ResumeData {
    return {
        id: crypto.randomUUID(),
        title: "Your Name - Resume",
        templateId: "timeline",
        personalInfo: {
            fullName: "Your Name Here",
            jobTitle: "Your Job Title Here",
            email: "your.email@example.com",
            phone: "Your Phone Number Here",
            location: "Your Location Here",
            website: "Your Website Here",
            linkedin: "Your LinkedIn Profile Here",
            github: "Your GitHub Profile Here",
            summary:
                "With overall 12 years of experience in software engineering using agile methodologies. Experience on AWS cloud platform and knowledge on high level architectural design working as full stack developer. Ability to adapt, multitask and motivated the team forward with new technologies through proven ability to understand and implement the requirements and go beyond the client expectations.",
            avatarUrl: "",
        },
        experience: [
            {
                id: "exp-1",
                company: "MassMutual India",
                position: "Technical Architect",
                location: "Hyderabad, India",
                startDate: "11/2024",
                endDate: "",
                current: true,
                description:
                    "• Served as solution architect across multiple projects, owning end-to-end technical direction\n• Improved application performance by resolving bottlenecks via caching and RTK-focused optimizations\n• Defined a branching and release strategy to enable faster, safer production hotfixes\n• Established full-stack architecture standards, including coding standards and reference documentation\n• Created HLD/LLD diagrams to align stakeholders and guide implementation\n• Dockerized multiple applications to streamline deployment and ensure environment parity\n• Delivered key integrations: MCP client/server for multi-org insurance form retrieval, plus DocuSign signing packages with Kafka-based status tracking for downstream processing and analytics, while mentoring developers and improving DX with Left hook, Redoc, and Biome",
            },
            {
                id: "exp-2",
                company: "EA Games @Maantic Global",
                position: "Senior Technical Lead",
                location: "Hyderabad, India",
                startDate: "11/2023",
                endDate: "10/2024",
                current: false,
                description:
                    "• Led implementation of an existing EA Games Help Center in Next.js, delivering UI and integrations to spec. Produced lightweight architecture/design docs to align the team and guide implementation decisions.\n• Owned sprint execution: drove sprint goals, facilitated reviews, and ensured predictable delivery.\n• Managed and mentored a 6–8 member team, providing day-to-day technical leadership.\n• Broke down epics into actionable stories, estimated effort, and allocated work effectively.\n• Enforced SOLID principles through regular code reviews and consistent engineering standards.\n• Worked within a modern stack: React, Next.js, monorepo (pnpm), Docker, CI/CD, Figma, and Contentful-driven content.\n• Environment: Nextjs, React, Docker, Vscode",
            },
            {
                id: "exp-3",
                company: "PruTech Solutions",
                position: "Technical Lead",
                location: "Hyderabad, India",
                startDate: "06/2023",
                endDate: "10/2023",
                current: false,
                description:
                    "• Built a Stripe-based payment solution in ReactJS for a client application.\n• Implemented add-to-cart functionality using GraphQL with ReactJS.\n• Developed responsive UI layouts using HTML, CSS, and SCSS.\n• Added global error handling leveraging AEM data attributes and Commerce API error responses.\n• Implemented add/remove cart flows with robust error handling based on stock availability.\n• Environment: React, GraphQL, HTML, CSS",
            },
            {
                id: "exp-4",
                company: "ValueLabs",
                position: "Module Lead",
                location: "Hyderabad, India",
                startDate: "07/2020",
                endDate: "03/2023",
                current: false,
                description:
                    "• Built a lead-capture pipeline integrating Unbounce and DynamoDB for reliable storage and retrieval.\n• Provisioned and managed AWS infrastructure using SAM/CloudFormation across API Gateway, CloudWatch, IAM, EC2, and supporting services.\n• Delivered reusable REST APIs for multiple teams, improved performance via caching, and executed database migrations.\n• Automated deployments with AWS CodeBuild/CodePipeline, implemented scheduled Node cron workflows, and led a team of 5 through requirements and delivery.\n• Environment: AWS, Typescript, SLS, Mongo, VsCode, Ubuntu, Bash, Nodejs",
            },
            {
                id: "exp-5",
                company: "EPAM Systems",
                position: "Senior Software Engineer",
                location: "Hyderabad, India",
                startDate: "02/2019",
                endDate: "07/2020",
                current: false,
                description:
                    "• Built micro-frontend modules for Thomson Reuters, delivering UI features in an Angular 7 stack.\n• Implemented data integration via GraphQL calls to fetch and render backend content.\n• Led a complex initiative to deliver a platform-agnostic date-format solution in NodeJS.\n• Migrated legacy services from .NET to NodeJS, while mentoring 2–3 team members.\n• Environment: Angular, Typescript, GraphQL, Windows, VsCode",
            },
            {
                id: "exp-6",
                company: "ValueLabs",
                position: "Senior Software Engineer",
                location: "Hyderabad, India",
                startDate: "09/2017",
                endDate: "01/2019",
                current: false,
                description:
                    "• Collaborated within a 12-member Agile team to deliver end-to-end client solutions.\n• Drove revenue growth by building tailored ad experiences using the Google Ads framework on WebMD.\n• Implemented targeted ad placements using vanilla JavaScript and the Google GPT library.\n• Environment: Windows and VS Code",
            },
            {
                id: "exp-7",
                company: "Ozonetel Communications",
                position: "Software Engineer",
                location: "Hyderabad, India",
                startDate: "07/2016",
                endDate: "02/2017",
                current: false,
                description:
                    "• Built a handcrafted, responsive UI using modern CSS (Flexbox and Grid) with clean HTML structure.\n• Developed Node.js/Express APIs to power core application features and data access.\n• Implemented ReactJS views to fetch and display user data from the backend.\n• Environment: Reactjs, MongoDB, Java",
            },
            {
                id: "exp-8",
                company: "Intense Technologies",
                position: "Software Engineer",
                location: "Hyderabad, India",
                startDate: "07/2013",
                endDate: "02/2016",
                current: false,
                description:
                    "• Developed Java-based web services to support core application functionality.\n• Implemented JSP/Servlet components for server-side rendering and request handling.\n• Built BPMN workflows using Joints to model and automate business processes.\n• Designed responsive UI layouts to ensure consistent behavior across devices.\n• Environment: Java, JSP servlets, JointJs, Angular 1.5, d3.js",
            },
        ],
        education: [
            {
                id: "edu-1",
                institution: "Aurora degree college",
                degree: "Bachelors degree",
                field: "",
                location: "",
                startDate: "2003",
                endDate: "2006",
                gpa: "",
                description: "",
            },
            {
                id: "edu-2",
                institution: "University of Ballarat",
                degree: "Masters in IT",
                field: "",
                location: "",
                startDate: "2006",
                endDate: "2008",
                gpa: "",
                description: "",
            },
            {
                id: "edu-3",
                institution: "NMIT Melbourne, Australia",
                degree: "Diploma in programming and Networking",
                field: "",
                location: "",
                startDate: "2010",
                endDate: "2012",
                gpa: "",
                description: "",
            },
        ],
        skills: [
            {
                id: "skill-1",
                name: "Backend",
                skills: [
                    "NodeJS",
                    "ExpressJS",
                    "NestJS",
                    "GraphQL",
                    "REST API",
                    "Typescript",
                    "Java",
                    "Bash",
                ],
            },
            {
                id: "skill-2",
                name: "Frontend",
                skills: [
                    "ReactJS",
                    "Next.js",
                    "Angular",
                    "JavaScript",
                    "HTML5",
                    "CSS grid layout/Flexbox",
                    "Tailwind",
                    "Bootstrap",
                    "Mantine",
                ],
            },
            {
                id: "skill-3",
                name: "Cloud & DevOps",
                skills: [
                    "AWS",
                    "AWS Lambda",
                    "Docker",
                    "Kubernetes",
                    "Terraform",
                    "CI/CD",
                    "Jenkins",
                    "Webpack",
                ],
            },
            {
                id: "skill-4",
                name: "Databases & Tools",
                skills: [
                    "MongoDB",
                    "SQL",
                    "Redis",
                    "Algolia",
                    "Git",
                    "Monorepo",
                    "MCP",
                    "SEO",
                    "Payload CMS",
                ],
            },
        ],
        projects: [
            {
                id: "proj-1",
                name: "Client - MassMutual India",
                url: "",
                startDate: "2024",
                endDate: "",
                current: true,
                description:
                    "As Technical Architect, led End-to-end solution architecture across multiple projects—driving performance and release improvements, standardizing full-stack practices and designs, enabling reliable deployments via Docker, and delivering critical integrations while mentoring teams and improving developer experience.\n\n• Delivered consistent, scalable solutions across multiple projects by setting technical direction and aligning stakeholders early, reducing rework and improving delivery predictability.\n• Improved user experience and system stability by removing key performance bottlenecks (caching + RTK optimizations), resulting in faster, smoother critical flows.\n• Reduced production risk and downtime by introducing a clear branching/release strategy, enabling quicker and safer hotfix releases.\n• Increased engineering consistency and onboarding speed by establishing full-stack standards (coding standards + reference docs) that teams could follow across services.\n• Improved clarity and execution by creating HLD/LLD diagrams, helping teams implement faster with fewer misunderstandings and better design alignment.\n• Streamlined deployments and minimized \"works on my machine\" issues by Dockerizing applications and ensuring environment parity across dev/test/prod.\n• Enabled real business operations with key integrations: faster insurance form discovery for CSRs via MCP client/server, reliable DocuSign signing workflows with Kafka-based status tracking for downstream analytics/processing, plus stronger team output through mentoring and improved DX (Lefthook, Redoc, Biome).",
                technologies: [],
            },
            {
                id: "proj-2",
                name: "Client - EA Games @Maantic",
                url: "",
                startDate: "11/2023",
                endDate: "",
                current: true,
                description:
                    "Implement Help page for EA Games fan base\n\n• Implemented the project from scratch in mono repo using turborepo with pnpm workspaces\n• Created multiple microfrontends and establish communication through nextjs module federation plugin\n• Enabled Loading of dynamic modules chucks as remotes using webpack federation modules\n• Isolate shell layouts and implement re-useable components as pnpm packages\n• Added foundational base for project with features such as husky, react loading skeleton, story book, plop generators, cicd pipelines, docker base images etc\n• Generate a Nextjs standalone build to be used as docker containers\n• Adapt to best coding standards, follow solid principles, regular code reviews and coding guideline\n• Optimized the CICD pipeline to enable faster deployments of mono repo",
                technologies: [],
            },
            {
                id: "proj-3",
                name: "Client - iSelect Australia @ValueLabs",
                url: "",
                startDate: "04/2022",
                endDate: "",
                current: true,
                description:
                    "Capture and process leads for insurance domain\n\n• Capture leads using from unbounce form.\n• Push them into SQS queue and save it in to DynamoDB using lambda handler.\n• Apply security using IP whitelisting inside resource policy of API gateway.\n• Set up lambda in to VPC to access the DynamoDB using gateway endpoint.\n• Create lambda custom authorizer to authorize the token in query string.\n• Create and run schema validation using JOI schema.\n• Generate secured pre-signed URLs with TTL using AWS SDK.\n• Regular peer review and mentoring the team when required.",
                technologies: [],
            },
            {
                id: "proj-4",
                name: "Client - Altus group @ValueLabs",
                url: "",
                startDate: "01/2022",
                endDate: "04/2022",
                current: false,
                description:
                    "(App portfolio project) - AWS serverless and Angular micro front ends\n\n• Create lambda handler functions that triggers SQS events for User role provisioning or unprovisioning.\n• Created utility packages holding reusable functionality such as logger, Postgres db connections and closing functionality, common exception handling.\n• Deployed utility NPM package into Jfrog private repository.\n• Build and deploy the code using AWS code build and deploy pipeline.\n• Create custom docker image with Ubuntu base and liquibase jar to perform db migrations, unit and integration tests.\n• Write bash scripts to automate the db migration using liquibase.\n• Write unit test cases using mocha and integration using Jest.",
                technologies: [],
            },
            {
                id: "proj-5",
                name: "Client - Altus group @ValueLabs",
                url: "",
                startDate: "07/2020",
                endDate: "01/2022",
                current: false,
                description:
                    "(Shared services project) - Formulated enterprise level services for multiple teams to consume.\n\n• Developed APIs using NodeJS, Express.js and MongoDB(Mongoose).\n• Designed Mongoose database schemas.\n• Implemented Express.js routes and route validations using JSON schema validator.\n• Performed database collection migrations using NPM mongression library. Also, optimized performance using Redis cache.\n• Created API versioning Express.js API route mechanism and provision users using RabbitMQ queues.\n• Compose Jenkins pipeline and deploy images into ECR repositories in AWS.\n• Created AWS Log groups, monitor and debug CloudWatch using insights.",
                technologies: [],
            },
            {
                id: "proj-6",
                name: "Client - Thomson Reuters @Epam systems",
                url: "",
                startDate: "2019",
                endDate: "2020",
                current: false,
                description:
                    "Display financial data to end users on Excel.\n\n• Migrated from legacy code base to Angular and NodeJS.\n• Created Angular components from scratch.\n• Designed custom Angular component to have combination of search, dropdown and select input.\n• Call HTTP services to fetch XML data, parse into JSON to display on Angular components.\n• Enhance performance of app by splitting requests into five asynchronous requests at a time.\n• Parse the custom Excel formulas to delegate the request and fetch the data.",
                technologies: [],
            },
            {
                id: "proj-7",
                name: "Client - WebMD @ValueLabs",
                url: "",
                startDate: "2017",
                endDate: "2019",
                current: false,
                description:
                    "Increased revenue for client by placing targeted Ads on WebMD health site.\n\n• Worked on google GPT library to display ads on website.\n• Tech stack was JavaScript, jQuery and GPT mainly to place different types of Ads.\n• Design responsive containers to hold Ad information.\n• Write scroll based Ads using jQuery events.\n• Write units using mocha and chai.",
                technologies: [],
            },
            {
                id: "proj-8",
                name: "Client - product based @Ozonetel communications",
                url: "",
                startDate: "2016",
                endDate: "2017",
                current: false,
                description:
                    "Developed website for IVR product called KooKoo.\n\n• Built responsive website from scratch using HTML5, CSS Flex and CSS grid layout.\n• Worked on full stack development using RiotJS on front-end and NodeJS, Express.js and MongoDB on backend.",
                technologies: [],
            },
        ],
        additionalExperience: [
            {
                id: "addl-1",
                name: "Educational app",
                url: "https://www.whatsnxt.in",
                startDate: "11/2022",
                endDate: "",
                current: true,
                description:
                    "Overview: Online Video based learning website along with articles and tutorial series.\n\nFeatures:\nEnabled Content authoring such as articles and tutorial series using Tiptap rich text editor\nCreated course builder to create courses, review and publish seamlessly\nEnable users to comment, like, dislike and report on the blog with nesting depth of 3\nAssets are cached using CDN and are uploaded using web workers on FE and BE\nSocial share to multiple websites as user and admin\nGoogle Analytics using partytown webworker\nRazorpay payment gateway to purchase courses\nSend email via nodemailer with retry mechanism\nLab feature: Drag and drop shapes to create SVG based quizzes for students\nAWS EventBridge + Lambda to clean up dangling images in S3\n\nSecurity:\nImplemented login using httpOnly JWT cookie and google login using passport\nAdded open telemetry sentry config for tracing and performance monitoring\nImplemented security features to prevent XSS, CSRF, Rate limiting and CORS\nImage safety scanning using Tensor flow\n\nOptimisation:\nOptimised the site by checking LCP and FCP using chrome tools\nEnable caching and search using Algolia\nImplemented Redis cache and cache invalidation based on route keys\nEnabled web vitals to track performance\nSite is SEO optimised and performant using on light house scores\n\nDeployment:\nFrontend app is deployed on Vercel platform\nBackend app is deployed as Docker containers on AWS EC2 using Terraform\n\nEnvironment: NextJS 15, Redux Tool Kit, Mantine UI, Algolia, Mongo, Express, Redis, AWS, EC2, ALB, Docker, Terraform, Node.JS, Swagger and ExpressJs, Tensor flow, Antigravity, Github Speckit\n\nArchitecture:\nHLD: https://www.whatsnxt.in/HLD.svg\nLLD: https://www.whatsnxt.in/LLD.svg",
                technologies: [],
            },
            {
                id: "addl-2",
                name: "Marketplace App",
                url: "https://www.choicexchange.in",
                startDate: "06/2024",
                endDate: "",
                current: true,
                description:
                    "An online marketplace for buying and selling products.",
                technologies: [],
            },
            {
                id: "addl-3",
                name: "Curated content",
                url: "https://www.curatedreels.com",
                startDate: "2024",
                endDate: "",
                current: true,
                description:
                    "A curated content platform for discovering and sharing short-form video content.",
                technologies: [],
            },
            {
                id: "addl-4",
                name: "Minute Menus",
                url: "",
                startDate: "2024",
                endDate: "",
                current: true,
                description:
                    "A recipe and menu planning application.",
                technologies: [],
            },
        ],
        certifications: [
            {
                id: "cert-1",
                name: "AWS certified cloud practitioner",
                issuer: "Amazon Web Services",
                issueDate: "",
                expiryDate: "",
                credentialId: "",
                credentialUrl: "",
            },
            {
                id: "cert-2",
                name: "AWS certified developer associate",
                issuer: "Amazon Web Services",
                issueDate: "",
                expiryDate: "",
                credentialId: "",
                credentialUrl: "",
            },
            {
                id: "cert-3",
                name: "AWS certified architect associate",
                issuer: "Amazon Web Services",
                issueDate: "",
                expiryDate: "",
                credentialId: "",
                credentialUrl: "",
            },
        ],
        languages: [],
        customSections: [],
        sectionOrder: DEFAULT_SECTION_ORDER,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    };
}
