services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: "whatsnxt"
    image: "whatsnxt:dev-v1.59"
    env_file:
      - .env.dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis-dev
    networks:
      - app
  
  redis-dev:
    container_name: redis-dev
    image: redis
    command: --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app
    volumes:
      - redis-dev:/data

  redis-commander-dev:
    container_name: redis-commander-dev
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander
    env_file:
      - .env.dev
    depends_on:
      - redis-dev
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - app

volumes:
  redis-dev:
    external: false

networks:
  app:
    name: app