services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: "whatsnxt"
    image: "whatsnxt:prod-v4.357"
    env_file:
      - .env.prod
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis-prod
    networks:
      - app
  
  redis-prod:
    container_name: redis-prod
    image: redis
    command: --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app
    volumes:
      - redis-prod:/data

  redis-commander-prod:
    container_name: redis-commander-prod
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander
    env_file:
      - .env.prod
    depends_on:
      - redis-prod
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - app

volumes:
  redis-prod:
    external: false

networks:
  app:
    name: app